-- ============================================================================
-- ENHANCED MASTER LEDGER SYSTEM - Additional Fields
-- ============================================================================
-- Adds missing fields from original feature requirements:
-- - Full inventory details (description, price, measurements, variants)
-- - Sales sync features (shipping labels, delisting automation)
-- - Invoicing system for non-platform sales
-- - SKU auto-generation support
--
-- Date: 2026-01-21
-- ============================================================================

-- ============================================================================
-- 1️⃣ INVENTORY MASTER ENHANCEMENTS
-- ============================================================================

-- Add missing inventory fields
ALTER TABLE inventory_master
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS price DECIMAL(10,2),  -- Current asking price
ADD COLUMN IF NOT EXISTS measurements TEXT,     -- JSON: {"length": 10, "width": 8, "height": 6, "unit": "inches"}
ADD COLUMN IF NOT EXISTS variants TEXT,         -- JSON array: [{"size": "S", "color": "red", "sku": "ABC-S-R"}]
ADD COLUMN IF NOT EXISTS auto_sku BOOLEAN DEFAULT FALSE,  -- Whether SKU was auto-generated
ADD COLUMN IF NOT EXISTS duplicate_check_mode TEXT DEFAULT 'detect';  -- detect, sync, ignore

COMMENT ON COLUMN inventory_master.description IS 'Full item description';
COMMENT ON COLUMN inventory_master.price IS 'Current asking price for this item';
COMMENT ON COLUMN inventory_master.measurements IS 'JSON object with item measurements';
COMMENT ON COLUMN inventory_master.variants IS 'JSON array for multi-variant items (size/color combinations)';
COMMENT ON COLUMN inventory_master.auto_sku IS 'True if SKU was auto-generated by the system';
COMMENT ON COLUMN inventory_master.duplicate_check_mode IS 'How to handle duplicates: detect, sync, ignore';

-- Expand status to match original requirements
COMMENT ON COLUMN inventory_master.status IS 'Inventory status: draft, active, sold, shipped, archived';


-- ============================================================================
-- 2️⃣ SALES LEDGER ENHANCEMENTS
-- ============================================================================

-- Add sales sync and automation fields
ALTER TABLE sales_ledger
ADD COLUMN IF NOT EXISTS shipping_label_url TEXT,  -- Link to shipping label from platform
ADD COLUMN IF NOT EXISTS cogs DECIMAL(10,2),       -- Cost of Goods Sold (alias for cost_basis)
ADD COLUMN IF NOT EXISTS delisting_scheduled_at TIMESTAMP,  -- When auto-delist is scheduled (15 min delay)
ADD COLUMN IF NOT EXISTS delisted_at TIMESTAMP,    -- When item was actually delisted
ADD COLUMN IF NOT EXISTS auto_delisted BOOLEAN DEFAULT FALSE,  -- Whether delisting was automated
ADD COLUMN IF NOT EXISTS item_storage_location TEXT;  -- Fetched from inventory at sale time

COMMENT ON COLUMN sales_ledger.shipping_label_url IS 'URL to shipping label (from platform API)';
COMMENT ON COLUMN sales_ledger.cogs IS 'Cost of Goods Sold - copied from inventory cost_basis';
COMMENT ON COLUMN sales_ledger.delisting_scheduled_at IS '15-minute delay timestamp before auto-delisting';
COMMENT ON COLUMN sales_ledger.delisted_at IS 'Timestamp when item was delisted from other platforms';
COMMENT ON COLUMN sales_ledger.auto_delisted IS 'True if delisting was performed automatically';
COMMENT ON COLUMN sales_ledger.item_storage_location IS 'Storage location copied from inventory at sale time';


-- ============================================================================
-- 3️⃣ SHIPPING LEDGER ENHANCEMENTS
-- ============================================================================

-- Add shipping label URL
ALTER TABLE shipping_ledger
ADD COLUMN IF NOT EXISTS shipping_label_url TEXT,  -- URL to download/view label
ADD COLUMN IF NOT EXISTS label_format TEXT DEFAULT 'pdf';  -- pdf, png, zpl, etc.

COMMENT ON COLUMN shipping_ledger.shipping_label_url IS 'Direct URL to shipping label';
COMMENT ON COLUMN shipping_ledger.label_format IS 'Format of shipping label: pdf, png, zpl';


-- ============================================================================
-- 4️⃣ INVOICING SYSTEM
-- ============================================================================
-- For Facebook Marketplace, local sales, DM sales, etc.

CREATE TABLE IF NOT EXISTS invoices (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),

    -- Identity
    invoice_id TEXT UNIQUE NOT NULL,             -- e.g., "INV-2024-001"
    invoice_number TEXT NOT NULL,                -- User-facing invoice number
    master_item_id TEXT REFERENCES inventory_master(master_item_id),

    -- Invoice details
    invoice_date DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE,

    -- Customer info
    buyer_name TEXT NOT NULL,
    buyer_email TEXT,
    buyer_phone TEXT,
    buyer_address TEXT,                          -- Full address as text or JSON

    -- Line items (can be JSON for multiple items)
    items TEXT NOT NULL,                         -- JSON array: [{"title": "...", "qty": 1, "price": 25.00}]

    -- Money
    currency TEXT DEFAULT 'USD',
    subtotal DECIMAL(10,2) NOT NULL,
    tax_rate DECIMAL(5,4) DEFAULT 0,             -- e.g., 0.0825 for 8.25%
    tax_amount DECIMAL(10,2) DEFAULT 0,
    shipping_amount DECIMAL(10,2) DEFAULT 0,
    discount_amount DECIMAL(10,2) DEFAULT 0,
    total_amount DECIMAL(10,2) NOT NULL,         -- Final amount due

    -- Payment
    payment_method TEXT,                         -- cash, venmo, paypal, zelle, etc.
    payment_status TEXT DEFAULT 'unpaid',        -- unpaid, partial, paid, refunded
    paid_amount DECIMAL(10,2) DEFAULT 0,
    paid_date DATE,

    -- Documents
    pdf_url TEXT,                                -- Generated invoice PDF URL
    pdf_generated BOOLEAN DEFAULT FALSE,
    sent_via TEXT,                               -- email, link, text, in-person
    sent_at TIMESTAMP,

    -- Status
    status TEXT DEFAULT 'draft',                 -- draft, sent, paid, overdue, cancelled

    -- Auto-mark inventory
    inventory_marked_sold BOOLEAN DEFAULT FALSE,

    -- Metadata
    notes TEXT,
    terms TEXT,                                  -- Payment terms, return policy, etc.
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_invoices_user_id ON invoices(user_id);
CREATE INDEX idx_invoices_master_item_id ON invoices(master_item_id);
CREATE INDEX idx_invoices_invoice_id ON invoices(invoice_id);
CREATE INDEX idx_invoices_status ON invoices(status);
CREATE INDEX idx_invoices_payment_status ON invoices(payment_status);
CREATE INDEX idx_invoices_invoice_date ON invoices(invoice_date);

ALTER TABLE invoices ADD CONSTRAINT unique_invoice_id UNIQUE(invoice_id);

COMMENT ON TABLE invoices IS 'Invoice system for Facebook, local, and DM sales';
COMMENT ON COLUMN invoices.items IS 'JSON array of line items with title, quantity, price';
COMMENT ON COLUMN invoices.payment_status IS 'Payment status: unpaid, partial, paid, refunded';
COMMENT ON COLUMN invoices.inventory_marked_sold IS 'True if inventory was automatically marked as sold';


-- ============================================================================
-- HELPER FUNCTIONS FOR INVOICING
-- ============================================================================

-- Function to generate invoice_id
CREATE OR REPLACE FUNCTION generate_invoice_id(user_id_param INTEGER)
RETURNS TEXT AS $$
DECLARE
    year_part TEXT;
    seq_num INTEGER;
    inv_id TEXT;
BEGIN
    year_part := TO_CHAR(CURRENT_DATE, 'YYYY');

    SELECT COALESCE(MAX(
        CAST(SUBSTRING(invoice_id FROM 'INV-\d{4}-(\d+)') AS INTEGER)
    ), 0) + 1
    INTO seq_num
    FROM invoices
    WHERE user_id = user_id_param
      AND invoice_id LIKE 'INV-' || year_part || '-%';

    inv_id := 'INV-' || year_part || '-' || LPAD(seq_num::TEXT, 4, '0');
    RETURN inv_id;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- SKU AUTO-GENERATION FUNCTION
-- ============================================================================

-- Function to generate SKU with configurable pattern
CREATE OR REPLACE FUNCTION generate_auto_sku(
    user_id_param INTEGER,
    category_param TEXT DEFAULT NULL,
    brand_param TEXT DEFAULT NULL
)
RETURNS TEXT AS $$
DECLARE
    year_part TEXT;
    seq_num INTEGER;
    category_code TEXT;
    brand_code TEXT;
    sku_result TEXT;
BEGIN
    year_part := TO_CHAR(CURRENT_DATE, 'YY');  -- 2-digit year

    -- Generate category code (first 3 letters, uppercase)
    IF category_param IS NOT NULL THEN
        category_code := UPPER(SUBSTRING(category_param, 1, 3));
    ELSE
        category_code := 'GEN';  -- Generic
    END IF;

    -- Generate brand code (first 2 letters, uppercase)
    IF brand_param IS NOT NULL THEN
        brand_code := UPPER(SUBSTRING(brand_param, 1, 2));
    ELSE
        brand_code := '';
    END IF;

    -- Get next sequence number for this user
    SELECT COALESCE(MAX(
        CAST(REGEXP_REPLACE(sku, '[^0-9]', '', 'g') AS INTEGER)
    ), 0) + 1
    INTO seq_num
    FROM inventory_master
    WHERE user_id = user_id_param
      AND sku IS NOT NULL;

    -- Format: CAT-YY-BRAND-####
    IF brand_code != '' THEN
        sku_result := category_code || '-' || year_part || '-' || brand_code || '-' || LPAD(seq_num::TEXT, 4, '0');
    ELSE
        sku_result := category_code || '-' || year_part || '-' || LPAD(seq_num::TEXT, 4, '0');
    END IF;

    RETURN sku_result;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION generate_auto_sku IS 'Generates SKU in format: CAT-YY-BRAND-#### (e.g., CLO-24-NIK-0001)';


-- ============================================================================
-- TAX & ACCOUNTING VIEWS
-- ============================================================================

-- Monthly summary view
CREATE OR REPLACE VIEW monthly_summary AS
SELECT
    user_id,
    DATE_TRUNC('month', sale_date) AS month,
    COUNT(*) AS num_sales,
    SUM(gross_sale_amount) AS total_revenue,
    SUM(platform_fees + payment_processing_fees) AS total_fees,
    SUM(shipping_cost) AS total_shipping_costs,
    SUM(shipping_charged) AS total_shipping_collected,
    SUM(tax_collected) AS total_tax_collected,
    SUM(net_payout) AS total_payout,
    SUM(cogs) AS total_cogs,
    SUM(profit) AS total_profit,
    ROUND(AVG(profit), 2) AS avg_profit_per_sale,
    -- Profit margin
    CASE
        WHEN SUM(gross_sale_amount) > 0
        THEN ROUND((SUM(profit) / SUM(gross_sale_amount) * 100), 2)
        ELSE 0
    END AS profit_margin_pct
FROM sales_ledger
WHERE payout_status = 'paid'
GROUP BY user_id, DATE_TRUNC('month', sale_date)
ORDER BY month DESC;

COMMENT ON VIEW monthly_summary IS 'Monthly sales summary with profit calculations';


-- Year-end tax export view (1099-K reconciliation)
CREATE OR REPLACE VIEW tax_year_summary AS
SELECT
    user_id,
    EXTRACT(YEAR FROM sale_date) AS tax_year,
    platform,
    COUNT(*) AS num_transactions,
    SUM(gross_sale_amount) AS gross_receipts,      -- 1099-K reportable amount
    SUM(shipping_charged) AS shipping_collected,    -- May be included in 1099-K
    SUM(tax_collected) AS sales_tax_collected,
    SUM(platform_fees) AS total_platform_fees,
    SUM(payment_processing_fees) AS total_processing_fees,
    SUM(shipping_cost) AS total_shipping_expenses,
    SUM(cogs) AS total_cogs,                        -- For Schedule C
    SUM(net_payout) AS total_net_payout,
    SUM(profit) AS total_profit                     -- Net income for taxes
FROM sales_ledger
WHERE payout_status = 'paid'
GROUP BY user_id, EXTRACT(YEAR FROM sale_date), platform
ORDER BY tax_year DESC, platform;

COMMENT ON VIEW tax_year_summary IS 'Year-end tax summary for 1099-K reconciliation and Schedule C';


-- All listings export view (for CSV export with filters)
CREATE OR REPLACE VIEW all_listings_export AS
SELECT
    i.master_item_id,
    i.sku,
    i.title,
    i.description,
    i.category,
    i.subcategory,
    i.brand,
    i.model,
    i.color,
    i.size,
    i.condition,
    i.price AS current_price,
    i.cost_basis,
    i.quantity,
    i.storage_location,
    i.status,
    i.platform_listing_ids,
    i.photos,
    i.measurements,
    i.variants,
    i.acquired_date,
    i.created_at,
    -- Sales info if sold
    s.sale_date,
    s.platform AS sold_platform,
    s.gross_sale_amount AS sold_price,
    s.profit,
    -- Shipping info if shipped
    sh.tracking_number,
    sh.carrier,
    sh.delivery_status
FROM inventory_master i
LEFT JOIN sales_ledger s ON i.master_item_id = s.master_item_id
LEFT JOIN shipping_ledger sh ON s.transaction_id = sh.transaction_id;

COMMENT ON VIEW all_listings_export IS 'Complete listing export with sales and shipping data';


-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_inventory_price ON inventory_master(price) WHERE price IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sales_delisting ON sales_ledger(delisting_scheduled_at) WHERE delisting_scheduled_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_invoices_buyer ON invoices(buyer_name);
CREATE INDEX IF NOT EXISTS idx_invoices_due_date ON invoices(due_date) WHERE due_date IS NOT NULL;


-- ============================================================================
-- TRIGGERS FOR AUTOMATION
-- ============================================================================

-- Trigger to auto-calculate invoice total
CREATE OR REPLACE FUNCTION calculate_invoice_total()
RETURNS TRIGGER AS $$
BEGIN
    NEW.total_amount := NEW.subtotal + NEW.tax_amount + NEW.shipping_amount - NEW.discount_amount;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER invoice_calculate_total
    BEFORE INSERT OR UPDATE ON invoices
    FOR EACH ROW
    EXECUTE FUNCTION calculate_invoice_total();


-- Trigger to update timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER inventory_updated_at
    BEFORE UPDATE ON inventory_master
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER sales_updated_at
    BEFORE UPDATE ON sales_ledger
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER shipping_updated_at
    BEFORE UPDATE ON shipping_ledger
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER drafts_updated_at
    BEFORE UPDATE ON draft_listings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER invoices_updated_at
    BEFORE UPDATE ON invoices
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();


-- ============================================================================
-- DONE!
-- ============================================================================

COMMENT ON SCHEMA public IS 'Enhanced master ledger system with full feature support';
